CREATE TABLE categories
(
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name   VARCHAR(255)                             NOT NULL,
    prefix VARCHAR(2)                             NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

ALTER TABLE categories
    ADD CONSTRAINT uc_categories_name UNIQUE (name);

ALTER TABLE categories
    ADD CONSTRAINT uc_categories_prefix UNIQUE (prefix);
    