create TABLE assignment_status_histories
(
    id            UUID    NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    created_by    VARCHAR(255),
    updated_by    VARCHAR(255),
    assignment_id UUID    NOT NULL,
    status_id     INTEGER NOT NULL,
    CONSTRAINT pk_assignment_status_histories PRIMARY KEY (id)
);

create TABLE assignment_statuses
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_assignment_statuses PRIMARY KEY (id)
);

create TABLE assignments
(
    id            UUID    NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    created_by    VARCHAR(255),
    updated_by    VARCHAR(255),
    user_id       UUID    NOT NULL,
    asset_id      UUID    NOT NULL,
    assigned_date date    NOT NULL,
    status_id     INTEGER NOT NULL,
    note          VARCHAR(500),
    CONSTRAINT pk_assignments PRIMARY KEY (id)
);

alter table assignment_statuses
    add CONSTRAINT uc_assignment_statuses_name UNIQUE (name);

alter table assignments
    add CONSTRAINT FK_ASSIGNMENTS_ON_ASSET FOREIGN KEY (asset_id) REFERENCES assets (id);

alter table assignments
    add CONSTRAINT FK_ASSIGNMENTS_ON_STATUS FOREIGN KEY (status_id) REFERENCES assignment_statuses (id);

alter table assignments
    add CONSTRAINT FK_ASSIGNMENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

alter table assignment_status_histories
    add CONSTRAINT FK_ASSIGNMENT_STATUS_HISTORIES_ON_ASSIGNMENT FOREIGN KEY (assignment_id) REFERENCES assignments (id);

alter table assignment_status_histories
    add CONSTRAINT FK_ASSIGNMENT_STATUS_HISTORIES_ON_STATUS FOREIGN KEY (status_id) REFERENCES assignment_statuses (id);
